name: Build wxWidgets

on:
  push:
    branches:
      - "feat/ci"
#  pull_request:
#    branches:
#      - "ue3"

env:
  UE3_BUILD_DIR: ${{ github.workspace }}/_build
  UE3_OUTPUT_DIR: ${{ github.workspace }}/_build/out

jobs:
  # TODO: use a matrix instead, allows us to concurrently build
  # both release and debug at the same time, but I'm not sure how we could share
  # the output between both jobs for the package step
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Get cache
        id: cache-cmake
        uses: actions/cache@v3.3.3
        with:
          path: |
            ${{ env.UE3_BUILD_DIR }}/x64
          key: ${{ runner.os }}-${{ hashFiles('${{ env.UE3_BUILD_DIR }}/build.ps1', '**/CMakeLists.txt', '**/*.cmake', 'build/cmake/**' ) }}

      - name: Setup CMake projects
        if: steps.cache-cmake.outputs.cache-hit != 'true'
        shell: pwsh
        working-directory: ${{ env.UE3_BUILD_DIR }}
        run: ./build.ps1 -CI -BuildWin32:$false # Win32 builds are disabled for now

      - name: Build Win64 - Debug
        working-directory: ${{ env.UE3_BUILD_DIR }}/x64
        run: cmake --build . --config Debug

